[build-system]
build-backend = "hatchling.build"
requires = [
    "hatch-fancy-pypi-readme",
    "hatch-vcs",
    "hatchling",
]

[project]
name = "CNICA"
description = "A Python package to perform coupled non-negative independent component analysis."
keywords = [
    "CNICA",
]
license = "NIST-PD"
#license-files = [ "LICENSE" ]
paths = [ "LICENSE" ]
authors = [
    { name = "Robert J. S. Ivancic", email = "ivancic91@gmail.com" },
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: Public Domain",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
]
readme = { file = "README.md", content-type = "text/markdown" }
dynamic = [
    # "readme",
    "version",
]
dependencies = [
    "numpy>=1.24.0",
    "scipy>=1.10.0",
    "scikit-learn>=1.3.0",
]
urls.Documentation = "https://pages.nist.gov/CNICA/"
urls.Homepage = "https://github.com/Ivancic91/CNICA"

[dependency-groups]
dev = [
    { include-group = "dev-extras" },
    { include-group = "mypy" },
    { include-group = "test" },
    { include-group = "typing" },
    { include-group = "uvxrun" },
]
test = [
    { include-group = "test-extras" },
]
docs = [
    "autodocsumm",
    "myst-nb; python_version>'3.9'",
    "pyenchant",
    "sphinx>=5.3.0",
    "sphinx-book-theme",
    "sphinx-copybutton",
    "sphinxcontrib-spelling"
]
cog = [ "cogapp" ]
dev-extras = [
    "ipykernel",
    "ipython",
    "nbclient>=0.10.0",
    "nox>=2024.10.9",
    "pytest-accept",
]
docs-live = [
    "sphinx-autobuild",
    { include-group = "docs" },
]
mypy = [ "mypy>=1.15.0" ]
nbval = [ "nbval" ]
test-extras = [
    "pytest",
    "pytest-cov",
    "pytest-sugar",
    "pytest-xdist",
]
test-notebook = [
    { include-group = "nbval" },
    { include-group = "test-extras" },
]
typing = [
    "pylint",
    "pytest",
    { include-group = "uvxrun" },
]
uvxrun = [ "packaging" ]

[tool.hatch.version]
source = "vcs"
raw-options = { local_scheme = "no-local-version" }

[tool.hatch.build]
exclude = [
    ".*_cache",
    "docs/_build"
]

[tool.hatch.build.targets.wheel]
packages = ["src/cnica"]

#[tool.hatch.metadata.hooks.fancy-pypi-readme]
#content-type = "text/markdown"
#fragments = [
#    { path = "README.md" },
#    { path = "CHANGELOG.md" },
#    { path = "LICENSE" },
#]

[tool.check-wheel-contents]
toplevel = [ "cnica" ]
src_dir = [ "src" ]

[tool.pyproject-fmt]

# * Testing --------------------------------------------------------------------

[tool.pytest.ini_options]
addopts = [
    "--pyargs",
    "--cov-config=pyproject.toml",
]
testpaths = [
    "README.md",
    "cnica",
    "tests",
]

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
exclude_also = [
    "if TYPE_CHECKING:",
    "@overload",
]
omit = [
    "*/vendored/*",
    "*/_typing.py",
]
include = [
    "src/*",
]

[tool.coverage.paths]
source = [
    "src/",
    ".nox/**/site-packages/",
]

# * Typing ---------------------------------------------------------------------

[tool.mypy]
files = [
    "src",
    "tests",
]
show_error_codes = true
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
exclude = [
    ".eggs",
    ".tox",
    ".nox",
    ".venv",
    ".numba_cache",
    "docs",
]
check_untyped_defs = true
strict = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
    "scipy.*",
    "sklearn.*",
]

[tool.pyright]
include = [
    "src",
    "tests",
]
exclude = [
    "**/__pycache__",
    ".tox/**",
    ".nox/**",
    ".venv/**",
    "**/.mypy_cache",
    "**/.numba_cache",
]
strict = [
    "src",
    "tests",
    "noxfile.py",
    "tools/*.py",
]
pythonVersion = "3.11"
typeCheckingMode = "basic"
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownArgumentType = false

[tool.pytype]
inputs = [
    "src",
    "tests",
]

# * Dependency creation --------------------------------------------------------

[tool.pyproject2conda]
user_config = "config/userconfig.toml"
template_python = "requirements/py{py}-{env}"
template = "requirements/{env}"
python = "default"
channels = "conda-forge"
style = "yaml"
deps = "pip"

[tool.pyproject2conda.dependencies]
pytest-accept = { pip = true }

[tool.pyproject2conda.envs.dev]
groups = "dev"
style = [ "requirements", "yaml" ]

[tool.pyproject2conda.envs.test]
groups = "test"
python = "all"
style = [ "requirements", "yaml" ]

[tool.pyproject2conda.envs.test-extras]
groups = "test-extras"
python = "all"
skip_package = true
style = [ "requirements", "yaml" ]

[tool.pyproject2conda.envs.test-notebook]
groups = "test-notebook"
style = "requirements"

[tool.pyproject2conda.envs.docs]
groups = "docs"
style = "requirements"

[tool.pyproject2conda.envs.docs-live]
groups = "docs-live"
style = "requirements"

[tool.pyproject2conda.envs.typing]
groups = "typing"
python = "all"
style = "requirements"

[tool.pyproject2conda.envs.build]
groups = "build-system.requires"
skip_package = true
style = "requirements"

[tool.pyproject2conda.envs.uvxrun-tools]
reqs = [
    "conda-lock>=2.5.5",
    "grayskull>=2.5.3",
    "nbqa>=1.8.4",
    "pre-commit",
    "pyright>=1.1.396",
    "scriv",
    "twine>=5.0.0",
]
groups = "mypy"
skip_package = true
style = "requirements"

# * uv -------------------------------------------------------------------------

[tool.uv]
managed = true
default-groups = [ "dev" ]
fork-strategy = "requires-python"
required-version = ">=0.6.5"

[tool.uv.pip]
annotation-style = "line"

# * Other tools ----------------------------------------------------------------

[tool.scriv]
format = "md"
md_header_level = "2"
new_fragment_template = "file: changelog.d/templates/new_fragment.md.j2"

[tool.commitizen]
use_shortcuts = true

[tool.cruft]