test:
  imports:
    - CNICA
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Ivancic91/CNICA
  summary: A Python package to perform coupled non-negative independent component analysis.
  description: |
    A Python package to perform coupled non-negative independent component analysis.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ivancic91
